# Generated by Django 2.2 on 2019-12-10 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, verbose_name='Текст')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('email', models.CharField(max_length=100, verbose_name='Почта')),
                ('status', models.CharField(choices=[('new', 'новая'), ('checked', 'проверена')], default='new', max_length=20, verbose_name='Статус')),
                ('rating', models.PositiveIntegerField(default=0, verbose_name='Рейтинг')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
