# Generated by Django 2.2 on 2019-12-12 04:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('webapp', '0002_auto_20191212_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-date_create']},
        ),
    ]
